import {
  AccesoriesImg,
  AccesoriesIcon,
  BatteriesImg,
  BatteriesIcon,
  BrakesImg,
  BrakesIcon,
  CoolingImg,
  CoolIcon,
  ElectricImg,
  ElectricIcon,
  MotorImg,
  MotorIcon,
  FilterImg,
  FilterIcon,
  FuelImg,
  FuelIcon,
  HydraulicImg,
  HydraulicIcon,
  IgnImg,
  IgnIcon,
  VariosImg,
  VariosIcon,
  TiresImg,
  TiresIcon,
  TrnsImg,
  TransmisionIcon,
  UpImg,
  UsedBg,
  UpIcon,
  UsedImg,
  UsedIcon,
  DirecImg,
  DirecIcon,
} from "../../assets/img/parts/parts/index.jsx";

export const partsData = [
  {
    title: "Accesorios",
    img: AccesoriesImg,
    path: "/parts/accesorios",
    hover: AccesoriesIcon,
    backG: "",
    category_es: "Accesorios",
    category_en: "Accesories",
  },
  {
    title: "Baterias",
    img: BatteriesImg,
    path: "/parts/baterias",
    hover: BatteriesIcon,
    backG: "",
    category_es: "Baterias",
    category_en: "Bateries",
  },
  {
    title: "Frenos",
    img: BrakesImg,
    path: "/parts/frenos",
    hover: BrakesIcon,
    backG: "",
    category_es: "Frenos",
    category_en: "Brakes",
  },

  {
    title: "Enfriamiento",
    img: CoolingImg,
    path: "/parts/enfriamiento",
    hover: CoolIcon,
    backG: "",
    category_es: "Enfriamiento",
    category_en: "Cooling",
  },
  {
    title: "Eléctrico",
    img: ElectricImg,
    path: "/parts/electrico",
    hover: ElectricIcon,
    backG: "",
    category_es: "Eléctrico",
    category_en: "Electric",
  },
  {
    title: "Motor",
    img: MotorImg,
    path: "/parts/motor",
    hover: MotorIcon,
    backG: "",
    category_es: "Motor",
    category_en: "Engine",
  },
  {
    title: "Filtros",
    img: FilterImg,
    path: "/parts/filtros",
    hover: FilterIcon,
    backG: "",
    category_es: "Filtros",
    category_en: "Filters",
  },
  {
    title: "Combustible",
    img: FuelImg,
    path: "/parts/combustible",
    hover: FuelIcon,
    backG: "",
    category_es: "Combustible",
    category_en: "Fuel",
  },
  {
    title: "Hidráulico",
    img: HydraulicImg,
    path: "/parts/hidraulico",
    hover: HydraulicIcon,
    backG: "",
    category_es: "Hidráulico",
    category_en: "Hydraulic",
  },
  {
    title: "Encendido",
    img: IgnImg,
    path: "/parts/encendido",
    hover: IgnIcon,
    backG: "",
    category_es: "Encendido",
    category_en: "Ignition",
  },
  {
    title: "Varios",
    img: VariosImg,
    path: "/parts/varios",
    hover: VariosIcon,
    backG: "",
    category_es: "Varios",
    category_en: "Miscellaneus",
  },
  ,
  {
    title: "Neumáticos",
    img: TiresImg,
    path: "/parts/neumaticos",
    hover: TiresIcon,
    backG: "",
    category_es: "Neumáticos",
    category_en: "Tires",
  },
  {
    title: "Transmisión",
    img: TrnsImg,
    path: "/parts/transmision",
    hover: TransmisionIcon,
    backG: "",
    category_es: "Transmisión",
    category_en: "Transmission",
  },
  {
    title: "Montajes",
    img: UpImg,
    path: "/parts/montajes",
    hover: UpIcon,
    backG: "",
    category_es: "Montajes",
    category_en: "Upright",
  },
  {
    title: "Equipos de manipulación ",
    img: UsedImg,
    path: "/parts/equipos",
    hover: UsedIcon,
    backG: UsedBg,
    category_es: "Equipos de manipulación",
    category_en: "Handlings Equipments",
  },
  {
    title: "Dirección",
    img: DirecImg,
    path: "/parts/direccion",
    hover: DirecIcon,
    backG: "",
    category_es: "Dirección",
    category_en: "Steering",
  },
];
